app = "rise-and-grind"
primary_region = "yyz"

[build]

[[services]]
protocol = "tcp"
internal_port = 8080
auto_stop_machines = false
auto_start_machines = true
min_machines_running = 1

[[vm]]
cpu_kind = "shared"
cpus = 1
memory_mb = 512
